language: node_js
node_js:
- '5'
- '4'
script: npm run build
notifications:
  email:
    on_failure: change
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy:production
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: npm run deploy:staging
env:
  global:
  - secure: bOMf/uH5z4jAvFlJlMov0XbHPryuv8GVZKm1OBrpMoM+O25imEd+MiBuPkHQ/hrUQu4KCS0ZkkCC7NnajUXCJhvaGeK2NKZxNfSbJyyz2i+oI91zlO47PmpMm/aX7jmhLXm0XeW0oDBnoOlpCCc5SP9P3mlUuL62CY4NbQ4pGi15IFuOY+5JXtzy8zQl/3KaWGJvYLoL8W7AfakBrNVJaEU6yw2OeYooBsO3jrXWr+TbbGJM5sVMdKSxxDZ0xEQT1z7gaolUt2eSUmLNfm/hI5PeR+zGlfPwRy8JCKtVKEC9kZTVvttY4NE5OIc2ozO05Sv/omehh67DEov/mg24wD+gsr+o+OoPuvNyhJEGmSx6I71/UCdm1d3B8TmB4Qg3F/uxecLC9ypJ0k6jMpbXc6mn/yjmzHYG2BrsmuQqCXtEWVlhIf5akJx3hGTT1gFBdxvmozsNMCGtlB2Hrg5awtSwM+DtZmnSLVUxSp5g0NCr85Dak+TnwCPsDzogs91Fxvval3O/jS50MSNP4x6BeLL6xS5AZzJTMeRNZ1Z/SflCmXB+jX0ZkyMlLVZGhkXAivTNEY01B5NXVDCs9iNDpA2mVjojYYVoGSQ/J4JG5fKr//5owCG8J+fpS7u1KPbfjQXfTqJm4i+vNzBC1UL/NL2QC+5q2Iz7oaIrBLrFbbc=
  - secure: i77f11RPkjWTA1q67S8EwSAy1uWfkLhcS2JpzSfSwhJJ/wSj/npfBjOL9w0FAAjItYk/1Prc8qWm5HtQf+lGRNCHVk5nztYrXMGOTOyhPTiysRPrWNOx9uOVMZxq59IveYGzmEnZLrzHs59RfSZlSS399PFDlmUKkgutxRO58XRyfZIEJB9n57iA8Nas5Hhl0XZ0LRLwNWK35loULGjOm83O3QFt2J3TAHIZXuX2RelEimDmhLfOqOT3I2FGsV9Hzq/V7qcQsqSl6SGV+9vDDvXTBLW6gC2naZWxg/HaWsqXNb09I60R0OJk/+zuzqwp9/tOcnDqqeuKrr7wyhBqorl/cyOdRvtiXT7LbJBX7UD7zocxaCPJVxzmMuYIetvmNHc27ASqDdC7UjoRHZoJSB4CcIFczAtbKf3V6lgPd6qo7HMN6baG5lQznGlHOZ9rNi/43WV0AoNyl746i7/y/2SkX8RC1TVF4aqgEaOmO4H6SjUZoT3j6eNEhuCpoJ3Kbe615uP/57HSE/YNoJPPjeX5iCZVkrIqF5K6XhavpuD2Amzv9F1Spf/FMhq0OsNlcR4/KaRALbQTHv1LaHUsos4G9z2sLVDYsSf1L8chi6xPJI9jjUmRhv+MYDiuICbSr03jpNHFuxNYDvj4KlvSGqBTw6JYPdYYB74RyEjBFKQ=
  - secure: DS8EkM9W29Pt67c9f7sweRC8uryLoP1UVM6SbKCPBP29loUyUhLatBkFGzr0Uzk+Ak30wNtQBTYpL5ULvBxbECWCM9Gm3O4QmI2OrD2A/jKSGrqlY2dcQMj0sjbfavozjXRGFEUdNRz63EmQdTxRkUSrG2x7hNa7lJ7/XawTCx+OM4f6HuRr92s/KQn/vgKbtSPPbbtU7/rTLL9gSx5ZV6qCXIndqDxOEgfP/wOWS5uq/OAEYDiYgxFB/Cml3nhPiz+uH6OLKVojmNBHJwwM1eNLmwbIQBzzzFXb2zcGyDa5GTHQTIqS92R+7XYA7yZBQuVC2MbXWMaVSLG+/4pRXtwAcnPJJJ6XtbcKKIh4OYz90p6qt5cJW187a+ehKGA+rvK0/xLv8VB+Rc2fYYtkyTLf/UgzETSpGQJWgBlel7HH3TIGCFmQfDlyH7VnxIGbBcYlpJejzNBUrPbVMjfzSpuIaxduV81I4+HIQQCr6cPoMi+BTrYwJF6TX4hHPQRrRyHBENowAbinSX1V/dRZTckdWwO+zCvFnF+CeFEfiKHafuspf1nyBuFOdk8aJhO/RwCQpwGxujtW1sFnJ99aJh0NDyn5Dp3mgGRpGYlNYhfx/ED2hKneTMtc7O+t0lDk1tQI9NBUE5vx0C8i5pgtHYPtdhxrcs0z1zgSGAPdihI=
